### ISSUE TITLE
Fix overflowing content

### ISSUE THREAD

**Issue by gitcommitshow** [gitcommitshow/auth-jwt#6]
At [some places](https://auth-jwt--gitcommitshow.repl.co/jwt), content overflows. Test and fix

![Screenshot 2021-03-14 at 12 02 28](https://user-images.githubusercontent.com/56937085/111059638-289d1280-84bd-11eb-8e6c-5e57bea3e877.png)

**Comment by stefanus-ricky** [comment]
Hi, is this issue fixed already? Seems the page already have `overflow-wrap: anywhere;` so I can't reproduce the issue

**Comment by gitcommitshow** [comment]
> Hi, is this issue fixed already? Seems the page already have `overflow-wrap: anywhere;` so I can't reproduce the issue

No, it's not fixed yet

**Comment by aemann2** [comment]
Looks like it was only an issue on Safari after the `overflow-wrap` fix. I just fixed it in my clone, am putting in a PR now. 

(This is my first open source issue, please let me know if I'm doing something wrong.)

**Comment by gitcommitshow** [comment]
Congratulations on your first PR @aemann2
Thank you for contributing to open source.
